### ISSUE TITLE
Bundling snakestagram environment in electron

### ISSUE THREAD

**Issue by betatim** [nteract/snakestagram#14]
edit: To bundle a `snakestagram` environment in an electron app package/bundle we have to delete `env/bin/conda`, `env/bin/activate` and `env/bin/deactivate` as they are symlinks that point to outside locations. Discussion below.

---

Building an app bundle doesn't seem to work. Only tried on OSX. If I place a snakestagram (or even just `conda create -p foobar --copy python=3`) environment inside a directory that gets bundled up with an electron app I get the following error message (tested with nteract: `npm run dist` and placing the env in `example-notebooks/`):
```
Signing app (identity: gdb-cert)
Error: Command failed: codesign --verify --deep --verbose=2 --strict /Users/someone/nteract/nteract/dist/mac/nteract.app
--prepared:/Users/someone/nteract/nteract/dist/mac/nteract.app/Contents/Frameworks/nteract Helper NP.app
--prepared:/Users/someone/nteract/nteract/dist/mac/nteract.app/Contents/Frameworks/nteract Helper EH.app
--validated:/Users/someone/nteract/nteract/dist/mac/nteract.app/Contents/Frameworks/nteract Helper NP.app
--validated:/Users/someone/nteract/nteract/dist/mac/nteract.app/Contents/Frameworks/nteract Helper EH.app
--prepared:/Users/someone/nteract/nteract/dist/mac/nteract.app/Contents/Frameworks/nteract Helper.app
--validated:/Users/someone/nteract/nteract/dist/mac/nteract.app/Contents/Frameworks/nteract Helper.app
--prepared:/Users/someone/nteract/nteract/dist/mac/nteract.app/Contents/Frameworks/Squirrel.framework/Versions/Current/.
--prepared:/Users/someone/nteract/nteract/dist/mac/nteract.app/Contents/Frameworks/Mantle.framework/Versions/Current/.
--validated:/Users/someone/nteract/nteract/dist/mac/nteract.app/Contents/Frameworks/Mantle.framework/Versions/Current/.
--validated:/Users/someone/nteract/nteract/dist/mac/nteract.app/Contents/Frameworks/Squirrel.framework/Versions/Current/.
--prepared:/Users/someone/nteract/nteract/dist/mac/nteract.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/Current/.
--validated:/Users/someone/nteract/nteract/dist/mac/nteract.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/Current/.
--prepared:/Users/someone/nteract/nteract/dist/mac/nteract.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/.
--validated:/Users/someone/nteract/nteract/dist/mac/nteract.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/.
/Users/someone/nteract/nteract/dist/mac/nteract.app: invalid destination for symbolic link in bundle

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:484:12)
From previous event:
    at MacPackager.sign (/Users/someone/nteract/nteract/node_modules/electron-builder/out/macPackager.js:264:11)
    at /Users/someone/nteract/nteract/node_modules/electron-builder/src/macPackager.ts:81:26
From previous event:
    at /Users/someone/nteract/nteract/node_modules/electron-builder/src/macPackager.ts:81:10
    at next (native)
From previous event:
    at MacPackager.pack (/Users/someone/nteract/nteract/node_modules/electron-builder/out/macPackager.js:173:11)
    at /Users/someone/nteract/nteract/node_modules/electron-builder/src/packager.ts:234:22
From previous event:
    at Packager.doBuild (/Users/someone/nteract/nteract/node_modules/electron-builder/out/packager.js:351:11)
    at /Users/someone/nteract/nteract/node_modules/electron-builder/src/packager.ts:162:38
    at next (native)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at Packager.build (/Users/someone/nteract/nteract/node_modules/electron-builder/out/packager.js:257:11)
    at /Users/someone/nteract/nteract/node_modules/electron-builder/src/builder.ts:217:33
    at next (native)
From previous event:
    at build (/Users/someone/nteract/nteract/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/Users/someone/nteract/nteract/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

after some careful reading it complains about a symlink that is pointing somewhere that is invalid (presumably outside the bundle??)

**Comment by betatim** [comment]
Found this magic command in the bag of shell tricks for finding symlinks that point outside the current directory tree:
`for f in $(find . -type l ); do echo -n $(grealpath $f) && echo -n "|" && echo $f ; done | grep -v "^$(pwd)" | cut -d \| -f 2` (use realpath instead of grealpath on linux).

which points to `bin/{de}activate` and `bin/conda` which indeed point outside of the bundle.

**Comment by rgbkrk** [comment]
Yeah, we can't use any scripts directly - we have to invoke `path.join('bin', 'python')` directly within the bundle followed by `['-m', 'moduleName']`.

/cc @lgeiger

**Comment by rgbkrk** [comment]
Oh wait, reading again. It doesn't like when you _package_ it up because of symlinks. Would deleting them be ok?

**Comment by betatim** [comment]
Yes, deleting them makes the packager happy and directly calling python scripts still works.
